In [1]:
import json

In [2]:
gt_path = "sample_gt.json"
pd_path = "sample_pd.json"

In [3]:
with open(gt_path) as f1, open(pd_path) as f2:
    gt = json.load(f1)
    pred = json.load(f2)

In [4]:
from jsondiff import diff

differences = diff(gt, pred, syntax="explicit")
differences

{update: {'personal_info': {update: {'age': '1999 (26세)'}},
  'education': {0: {update: {'degree': '데이터사이언스학과'}}},
  'activities': {3: {update: {'period': ''}},
   4: {update: {'title': '산불 발생 확률 예측',
     'description': '세종대학교 캡스톤 디자인 과목 프로젝트. (교내 우수상 수상)\n기상, 지형, 인적 요소에 대한 이미지와 정형 데이터를 활용하여 산불 발생 확률을 예측\nCNN과 MLP를 이용하여 예측',
     'period': ''}},
   5: {update: {'period': ''}},
   insert: [(0,
     {'title': '패스트캠퍼스 부트캠프',
      'description': '패스트캠퍼스와 업스테이지가 주도하는 Upstage AI Lab이라 불리는 인공지능(AI) 부트캠프 교육과정에 참여하여 학부 생활 때 부족했던 개념 공부 및 다양한 사람들과의 프로젝트 및 협업을 통해 경험을 쌓았습니다.',
      'period': '2023.10 ~ 2024.04'}),
    (1,
     {'title': '선행시간에 따른 수위 예측',
      'description': '개인 프로젝트\n선행시간에 따른 잠수교의 수위를 예측하며 주요 인자를 파악하고 예측 성능 고도화\nOptuna, RandomForest, LGBM 을 이용한 예측',
      'period': ''})],
   delete: [4]},
  'certificates': {0: {update: {'score': 'Pass', 'date': '최종합격'}},
   1: {update: {'date': '2022.03'}}}}}

In [5]:
from langchain.evaluation.parsing.json_distance import JsonEditDistanceEvaluator

evaluator = JsonEditDistanceEvaluator()
result = evaluator.evaluate_strings(prediction=pred, reference=gt)

result

{'score': 0.48117489986648865}

In [6]:
import json
from deepdiff import DeepDiff

diff = DeepDiff(gt, pred, ignore_order=True)
diff

{'values_changed': {"root['personal_info']['age']": {'new_value': '1999 (26세)',
   'old_value': '24세'},
  "root['education'][0]['degree']": {'new_value': '데이터사이언스학과',
   'old_value': '4년제'},
  "root['activities'][4]['period']": {'new_value': '',
   'old_value': '2022.05 ~ 2023.05'},
  "root['activities'][1]['period']": {'new_value': '',
   'old_value': '2023.12 ~ 2024.01'},
  "root['activities'][3]['period']": {'new_value': '',
   'old_value': '2023.06 ~ 2023.07'},
  "root['certificates'][0]": {'new_value': {'name': '데이터분석준전문가(ADsP)',
    'score': 'Pass',
    'issuer': '한국데이터베이스진흥원',
    'date': '최종합격'},
   'old_value': {'name': '데이터분석준전문가(ADsP)',
    'score': '최종합격',
    'issuer': '한국데이터베이스진흥원',
    'date': '2022.03'}},
  "root['certificates'][1]": {'new_value': {'name': 'TOEIC',
    'score': '940점/PASS',
    'issuer': '영어',
    'date': '2022.03'},
   'old_value': {'name': 'TOEIC',
    'score': '940점/PASS',
    'issuer': '영어',
    'date': '2023.08'}}},
 'iterable_item_added': {"root['activities'][4]": {'title': '산불 발생 확률 예측',
   'description': '세종대학교 캡스톤 디자인 과목 프로젝트. (교내 우수상 수상)\n기상, 지형, 인적 요소에 대한 이미지와 정형 데이터를 활용하여 산불 발생 확률을 예측\nCNN과 MLP를 이용하여 예측',
   'period': ''}}}

In [7]:
from jycm.jycm import YouchamaJsonDiffer

ycm = YouchamaJsonDiffer(gt, pred)
diff_result = ycm.get_diff()
diff_result

{'just4vis:pairs': [{'left': {'title': '패스트캠퍼스 부트캠프',
    'description': '패스트캠퍼스와 업스테이지가 주도하는 Upstage AI Lab이라 불리는 인공지능(AI) 부트캠프 교육과정에 참여하여 학부 생활 때 부족했던 개념 공부 및 다양한 사람들과의 프로젝트 및 협업을 통해 경험을 쌓았습니다.',
    'period': '2023.10 ~ 2024.04'},
   'right': {'title': '패스트캠퍼스 부트캠프',
    'description': '패스트캠퍼스와 업스테이지가 주도하는 Upstage AI Lab이라 불리는 인공지능(AI) 부트캠프 교육과정에 참여하여 학부 생활 때 부족했던 개념 공부 및 다양한 사람들과의 프로젝트 및 협업을 통해 경험을 쌓았습니다.',
    'period': '2023.10 ~ 2024.04'},
   'left_path': 'activities->[2]',
   'right_path': 'activities->[0]'},
  {'left': '패스트캠퍼스와 업스테이지가 주도하는 Upstage AI Lab이라 불리는 인공지능(AI) 부트캠프 교육과정에 참여하여 학부 생활 때 부족했던 개념 공부 및 다양한 사람들과의 프로젝트 및 협업을 통해 경험을 쌓았습니다.',
   'right': '패스트캠퍼스와 업스테이지가 주도하는 Upstage AI Lab이라 불리는 인공지능(AI) 부트캠프 교육과정에 참여하여 학부 생활 때 부족했던 개념 공부 및 다양한 사람들과의 프로젝트 및 협업을 통해 경험을 쌓았습니다.',
   'left_path': 'activities->[2]->description',
   'right_path': 'activities->[0]->description'},
  {'left': '2023.10 ~ 2024.04',
   'right': '2023.10 ~ 2024.04',
   'left_path': 'activities->[2]->period',
   'right_path': 'activities->[0]->period'},
  {'left': '패스트캠퍼스 부트캠프',
   'right': '패스트캠퍼스 부트캠프',
   'left_path': 'activities->[2]->title',
   'right_path': 'activities->[0]->title'},
  {'left': {'title': '선행시간에 따른 수위 예측',
    'description': '개인 프로젝트\n선행시간에 따른 잠수교의 수위를 예측하며 주요 인자를 파악하고 예측 성능 고도화\nOptuna, RandomForest, LGBM 을 이용한 예측',
    'period': '2022.05 ~ 2023.05'},
   'right': {'title': '선행시간에 따른 수위 예측',
    'description': '개인 프로젝트\n선행시간에 따른 잠수교의 수위를 예측하며 주요 인자를 파악하고 예측 성능 고도화\nOptuna, RandomForest, LGBM 을 이용한 예측',
    'period': ''},
   'left_path': 'activities->[4]',
   'right_path': 'activities->[1]'},
  {'left': '개인 프로젝트\n선행시간에 따른 잠수교의 수위를 예측하며 주요 인자를 파악하고 예측 성능 고도화\nOptuna, RandomForest, LGBM 을 이용한 예측',
   'right': '개인 프로젝트\n선행시간에 따른 잠수교의 수위를 예측하며 주요 인자를 파악하고 예측 성능 고도화\nOptuna, RandomForest, LGBM 을 이용한 예측',
   'left_path': 'activities->[4]->description',
   'right_path': 'activities->[1]->description'},
  {'left': '2022.05 ~ 2023.05',
   'right': '',
   'left_path': 'activities->[4]->period',
   'right_path': 'activities->[1]->period'},
  {'left': '선행시간에 따른 수위 예측',
   'right': '선행시간에 따른 수위 예측',
   'left_path': 'activities->[4]->title',
   'right_path': 'activities->[1]->title'}],
 'list:add': [{'left': '__NON_EXIST__',
   'right': {'title': '문서 이미지 분류',
    'description': 'Upstage AI Lab에서 진행된 각종 문서 이미지를 분류하는 대회. | Rank: 2/13\n진단서, 이력서, 영수증 등의 다양한 문서 이미지를 올바르게 분류\nResNet, EfficientNet을 이용한 분류',
    'period': '2024.01 ~ 2024.02'},
   'left_path': '',
   'right_path': 'activities->[2]'},
  {'left': '__NON_EXIST__',
   'right': {'title': '아파트 실거래가 예측',
    'description': 'Upstage AI Lab에서 진행된 아파트 실거래가를 예측하는 대회 | Rank: 2/20\n서울시 아파트 실거래가를 다양한 데이터를 직접 수집하여 예측\nOptuna, CatBoost, LGBM, RandomForest를 이용한 예측',
    'period': ''},
   'left_path': '',
   'right_path': 'activities->[3]'},
  {'left': '__NON_EXIST__',
   'right': {'title': '산불 발생 확률 예측',
    'description': '세종대학교 캡스톤 디자인 과목 프로젝트. (교내 우수상 수상)\n기상, 지형, 인적 요소에 대한 이미지와 정형 데이터를 활용하여 산불 발생 확률을 예측\nCNN과 MLP를 이용하여 예측',
    'period': ''},
   'left_path': '',
   'right_path': 'activities->[4]'},
  {'left': '__NON_EXIST__',
   'right': {'title': '석유 소모량 예측',
    'description': '개인 프로젝트\n공장별 특징을 파악하여 공장에서 발생하는 석유 소모량을 예측하는 프로젝트\n군집화 및 LSTM을 이용하여 예측',
    'period': ''},
   'left_path': '',
   'right_path': 'activities->[5]'}],
 'list:remove': [{'left': {'title': '문서 이미지 분류',
    'description': 'Upstage AI Lab에서 진행된 각종 문서 이미지를 분류하는 대회. | Rank: 2/13\n진단서, 이력서, 영수증 등의 다양한 문서 이미지를 올바르게 분류\nResNet, EfficientNet을 이용한 분류',
    'period': '2024.01 ~ 2024.02'},
   'right': '__NON_EXIST__',
   'left_path': 'activities->[0]',
   'right_path': ''},
  {'left': {'title': '아파트 실거래가 예측',
    'description': 'Upstage AI Lab에서 진행된 아파트 실거래가를 예측하는 대회 | Rank: 2/20\n서울시 아파트 실거래가를 다양한 데이터를 직접 수집하여 예측\nOptuna, CatBoost, LGBM, RandomForest를 이용한 예측',
    'period': '2023.12 ~ 2024.01'},
   'right': '__NON_EXIST__',
   'left_path': 'activities->[1]',
   'right_path': ''},
  {'left': {'title': '석유 소모량 예측',
    'description': '개인 프로젝트\n공장별 특징을 파악하여 공장에서 발생하는 석유 소모량을 예측하는 프로젝트\n군집화 및 LSTM을 이용하여 예측',
    'period': '2023.06 ~ 2023.07'},
   'right': '__NON_EXIST__',
   'left_path': 'activities->[3]',
   'right_path': ''}],
 'value_changes': [{'left': '2022.05 ~ 2023.05',
   'right': '',
   'left_path': 'activities->[4]->period',
   'right_path': 'activities->[1]->period',
   'old': '2022.05 ~ 2023.05',
   'new': ''},
  {'left': '2022.03',
   'right': '최종합격',
   'left_path': 'certificates->[0]->date',
   'right_path': 'certificates->[0]->date',
   'old': '2022.03',
   'new': '최종합격'},
  {'left': '최종합격',
   'right': 'Pass',
   'left_path': 'certificates->[0]->score',
   'right_path': 'certificates->[0]->score',
   'old': '최종합격',
   'new': 'Pass'},
  {'left': '2023.08',
   'right': '2022.03',
   'left_path': 'certificates->[1]->date',
   'right_path': 'certificates->[1]->date',
   'old': '2023.08',
   'new': '2022.03'},
  {'left': '4년제',
   'right': '데이터사이언스학과',
   'left_path': 'education->[0]->degree',
   'right_path': 'education->[0]->degree',
   'old': '4년제',
   'new': '데이터사이언스학과'},
  {'left': '24세',
   'right': '1999 (26세)',
   'left_path': 'personal_info->age',
   'right_path': 'personal_info->age',
   'old': '24세',
   'new': '1999 (26세)'}]}

In [44]:
import math
from typing import Tuple
from jycm.operator import BaseOperator

class L2DistanceOperator(BaseOperator):
    __operator_name__ = "operator:l2distance"
    __event__ = "operator:l2distance"

    def __init__(self, path_regex, distance_threshold):
        super().__init__(path_regex=path_regex)
        self.distance_threshold = distance_threshold

    def diff(self, level: 'TreeLevel', instance, drill: bool) -> Tuple[bool, float]:
        distance = math.sqrt(
            (level.left["x"] - level.right["x"]) ** 2 + (level.left["y"] - level.right["y"]) ** 2
        )
        info = {
            "distance": distance,
            "distance_threshold": self.distance_threshold,
            "pass": distance < self.distance_threshold
        }


        #if not drill:
        instance.report(self.__event__, level, info)
        return distanc if info["pass"] else distance

In [46]:

from jycm.jycm import YouchamaJsonDiffer

left = {
    "distance_ok": {
        "x": 1,
        "y": 1
    },
    "distance_too_far": {
        "x": 5,
        "y": 5
    },
}

right = {
    "distance_ok": {
        "x": 2,
        "y": 2
    },
    "distance_too_far": {
        "x": 7,
        "y": 9
    },
}

ycm = YouchamaJsonDiffer(left, right, custom_operators=[
    L2DistanceOperator(f"distance.*", 3),
])
result = ycm.diff()

DiffLevelException: Error name 'distanc' is not defined [drill=False] when compare [{'left': {'x': 1, 'y': 1}, 'right': {'x': 2, 'y': 2}, 'left_path': ['distance_ok'], 'right_path': ['distance_ok']}]

In [51]:
from deepdiff import DeepDiff

diff = DeepDiff(gt, pred, ignore_order=True, get_deep_distance=True)
diff['deep_distance']

0.13872832369942195

In [2]:
import pandas as pd

data = pd.read_pickle("data/resume_data.pkl")
data

,text,labels,original_path
0,"## 배창현 신입\n\n남, 1999 (24세)\n\nmatthew624@naver...",/home/bch/Project/main_project/scout_partners/...,/home/bch/Project/main_project/scout_partners/...
1,## 이현우 (Hyunwoo Lee)\n\n생년월일: 1975년 9월 19일 (만 ...,/home/bch/Project/main_project/scout_partners/...,국문이력서(그림포함)-s1

In [1]:
import pandas as pd
data = pd.read_pickle("data/resume_data.pkl")
data

,text,labels,original_path
0,"## 배창현 신입\n\n남, 1999 (24세)\n\nmatthew624@naver...",/home/bch/Project/main_project/scout_partners/...,/home/bch/Project/main_project/scout_partners/...
1,## 이현우 (Hyunwoo Lee)\n\n생년월일: 1975년 9월 19일 (만 ...,/home/bch/Project/main_project/scout_partners/...,국문이력서(그림포함)-s1